
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA COMENTARIO IDENTIFICADOR NUMERO OPERADOR PALABRA_RESERVADA SIMBOLO_ESPECIAL\n    definicion_funcion : COMENTARIO definicion_funcion_no_comentario\n                       | definicion_funcion_no_comentario\n    \n    definicion_funcion_no_comentario : PALABRA_RESERVADA IDENTIFICADOR SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL parametros SIMBOLO_ESPECIAL\n                                     | PALABRA_RESERVADA IDENTIFICADOR SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL\n    \n    parametros : IDENTIFICADOR\n               | parametros SIMBOLO_ESPECIAL IDENTIFICADOR\n               | parametros SIMBOLO_ESPECIAL CADENA\n               | parametros SIMBOLO_ESPECIAL NUMERO\n               | parametros SIMBOLO_ESPECIAL OPERADOR\n    '
    
_lr_action_items = {'COMENTARIO':([0,],[2,]),'PALABRA_RESERVADA':([0,2,],[4,4,]),'$end':([1,3,5,10,12,],[0,-2,-1,-4,-3,]),'IDENTIFICADOR':([4,8,12,],[6,9,13,]),'SIMBOLO_ESPECIAL':([6,7,8,9,11,13,14,15,16,],[7,8,10,-5,12,-6,-7,-8,-9,]),'CADENA':([12,],[14,]),'NUMERO':([12,],[15,]),'OPERADOR':([12,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'definicion_funcion':([0,],[1,]),'definicion_funcion_no_comentario':([0,2,],[3,5,]),'parametros':([8,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> definicion_funcion","S'",1,None,None,None),
  ('definicion_funcion -> COMENTARIO definicion_funcion_no_comentario','definicion_funcion',2,'p_definicion_funcion','analizador_lexico.py',116),
  ('definicion_funcion -> definicion_funcion_no_comentario','definicion_funcion',1,'p_definicion_funcion','analizador_lexico.py',117),
  ('definicion_funcion_no_comentario -> PALABRA_RESERVADA IDENTIFICADOR SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL parametros SIMBOLO_ESPECIAL','definicion_funcion_no_comentario',6,'p_definicion_funcion_no_comentario','analizador_lexico.py',122),
  ('definicion_funcion_no_comentario -> PALABRA_RESERVADA IDENTIFICADOR SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL SIMBOLO_ESPECIAL','definicion_funcion_no_comentario',5,'p_definicion_funcion_no_comentario','analizador_lexico.py',123),
  ('parametros -> IDENTIFICADOR','parametros',1,'p_parametros','analizador_lexico.py',128),
  ('parametros -> parametros SIMBOLO_ESPECIAL IDENTIFICADOR','parametros',3,'p_parametros','analizador_lexico.py',129),
  ('parametros -> parametros SIMBOLO_ESPECIAL CADENA','parametros',3,'p_parametros','analizador_lexico.py',130),
  ('parametros -> parametros SIMBOLO_ESPECIAL NUMERO','parametros',3,'p_parametros','analizador_lexico.py',131),
  ('parametros -> parametros SIMBOLO_ESPECIAL OPERADOR','parametros',3,'p_parametros','analizador_lexico.py',132),
]
